# Generated by Django 5.2.4 on 2025-07-26 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimstatus',
            name='current_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimstatus',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('dm_review', 'DM Review Requested'), ('dm_approved', 'DM Approved'), ('om_review', 'OM Review Requested'), ('ar_review', 'AR Review'), ('om_approved', 'OM Approved'), ('ar_approved', 'AR Approved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
