# Generated by Django 5.2.4 on 2025-07-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eme', '0002_claimstatus_current_handler_claimstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimstatus',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('dm_review', 'DM Review Requested'), ('dm_approved', 'DM Approved'), ('om_review', 'OM Review Requested'), ('ar_review', 'AR Review'), ('om_approved', 'OM Approved'), ('ar_approved', 'AR Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
